### ISSUE TITLE
About the project

### ISSUE THREAD

**Issue by denysvitali** [haxelion/squid_decoder#2]
Hey @haxelion ,
thanks for your project.

I made an improved / extended version of your original project which you can find it [here](https://gtihub.com/denysvitali/squid_decoder).  
  
I added many things such as:
- Hierarchically sorted notes (exported/notebook-name/note-name.pdf)
![screenshot from 2017-10-10 21-35-00](https://user-images.githubusercontent.com/4939519/31407295-b6f45216-ae04-11e7-8d57-9068a471a8b5.png)
- Image Tool
- Highlight
- PDF Background

  
Should I make a PR to implement these features to your project too or do you want to keep it as this in order to have a "barebone project"?

**Comment by haxelion** [comment]
Wow ... this is not just an improvement, this is a whole other level 😲

I think it's better if you keep it on your GitHub since it's more yours than mine now 😅

I'll add a link at the top of the readme linking to your repo instead 😁

**Comment by haxelion** [comment]
Done.
I like it a lot, it's a really nice job!

**Comment by denysvitali** [comment]
Don't worry! Without your contribution the project would have never reached this level of awesomeness 🚀 .

Feel free to make PR / share your ideas if you still use the project. Currently (as per screenshots) I use it daily for my notes - it is really useful and squid doesn't seem to be able to handle the PDF generation, therefore a simple pipeline w/ Jenkins solves my issue, and moves the workload to my server instead. Plus, by default in Jenkins the artifacts are stored automatically. It's a win-win 😄
